# Generated by Django 4.2.11 on 2025-05-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="horario",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="horario",
            name="hora_inicio",
            field=models.CharField(
                choices=[
                    ("07h", "07h"),
                    ("08h", "08h"),
                    ("09h", "09h"),
                    ("10h", "10h"),
                    ("11h", "11h"),
                    ("12h", "12h"),
                    ("13h", "13h"),
                    ("14h", "14h"),
                    ("15h", "15h"),
                    ("16h", "16h"),
                    ("17h", "17h"),
                    ("18h", "18h"),
                    ("19h", "19h"),
                    ("20h", "20h"),
                    ("21h", "21h"),
                    ("22h", "22h"),
                    ("23h", "23h"),
                    ("00h", "00h"),
                ],
                max_length=5,
            ),
        ),
    ]
