# Generated by Django 4.2.11 on 2025-05-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desafios", "0002_horario_descricao_alter_horario_hora_inicio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="horario",
            unique_together={("dia", "hora_inicio")},
        ),
    ]
