# Generated by Django 4.2.11 on 2025-05-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desafios", "0003_alter_horario_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="horario",
            unique_together=set(),
        ),
    ]
